language: php

sudo: false
dist: trusty

git:
  depth: 3

addons:
  chrome: stable
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3

notifications:
  email: false
  slack:
    secure: LYT5ZTWPmcOR1iUxPIxn4G4GdW9dw86IWEdQ0WHf4XaDp0LMUh4yQI7lz+hrDNrLMp/7BeX1O11s3EmQ6rhGJvsc/7gCqzpg1weHPjzEdjhUPa8NcQwniUH2iUISYFaMs43Uh/J8MG/wlC1UfVdBOs3owS4Urbg5PTW9oB8t3+bppLP4AfeMCghAsKSpj/lt55lbhXgD3cR7tDG5xNFDYNQgjXlr8qVyhpDx//c7pv0X+CmGPwsGobReq5R4AP7/RLLKDxL7DMd6DiCpEi9CnaAU1XvWC8yKF954YN+44mTAc/AjUnAen3rxwFRxH9wFOxnwjBYWxaZ1sXV/2bEAjDmO0YDJG/t5TDvw4traNhMneb1pkAAsxr/e+CUsRFQHOZqZhYv/ua/+4/rzR6pavbyHzCu78lekdMOM+ytqH0gxDR00ID9nEJPCuBy5AyMeZrdpx96vH2jK1MixwWtu+zWK+6eyzZ9LV9CTvtyXRIJwK6KzUIrWcxhApmz+PgIrwr8ecbq4adcGS4mYXPRfmzQcoY7ouhMdNX6NgJ+PSzAQAzAHje9HA26P2bmoy8gDcdssd73fk8jrGNo2J4pD1KHk1Hv0rk7fqNEdlRqJYPzj14i3tRGrhCPP3YGGVVVELpDThpKr7DOQLhdnjc5yMhRqvkyihoMXMPXCxP/3Ztg=

branches:
  only:
    - master
    - "/^v[0-9\\.]+/"
    - "/^release-v[0-9\\.]+/"

cache:
  yarn: true
  directories:
    - "${HOME}/.composer/cache"
    - node_modules

stages:
  - name: check
    if: branch = master and tag IS blank and type IN (pull_request, api)
  - name: test
    if: branch = master and tag IS blank and type IN (pull_request, api)

jobs:
  fast_finish: true
  include:
    - stage: check
      language: php
      php: '7.3'
      env: APP_ENV=testing
      script: composer bin:phpcs
    - stage: check
      language: php
      php: '7.3'
      env: APP_ENV=testing
      script: composer bin:phpmd
    - stage: check
      language: node_js
      node_js: '12'
      dist: trusty
      script: composer bin:stylelint
    - stage: check
      language: node_js
      node_js: '12'
      dist: trusty
      script: composer bin:eslint


    - stage: test
      language: php
      php: '7.3'
      env: UPGRADE_NODE=true
      script: composer bin:phpunit
    - stage: test
      language: php
      php: '7.3'
      env: UPGRADE_NODE=true
      script: composer bin:dusk
    - stage: test
      language: node_js
      node_js: '12'
      dist: trusty
      script: composer bin:jest
