on:
  push:
    tags:
      - 'v*'

name: Release

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      CI: 1
      TRAVIS_BUILD_DIR: ${{ github.workspace }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 3
      - name: Run tests
        run: |
          bash bin/test/phpunit.sh
          bash bin/test/jest.sh
          bash bin/test/dusk.sh
      - uses: 8398a7/action-slack@v1
        with:
          type: failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()

  releases:
    name: Upload build files
    needs: test
    runs-on: ubuntu-latest
    env:
      TRAVIS_BUILD_DIR: ${{ github.workspace }}
      RELEASE_FILE: release.zip
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 3
      - name: Build
        run: bash bin/deploy/gh-releases.sh
      - name: Upload
        uses: technote-fork/action-gh-release@v1
        with:
          files: ${{ RELEASE_FILE }}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: 8398a7/action-slack@v1
        with:
          type: failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()

  pages:
    name: Publish GitHub Pages
    needs: test
    runs-on: ubuntu-latest
    env:
      TRAVIS_BUILD_DIR: ${{ github.workspace }}
      GH_PAGES_DIR: public/gh-pages
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 3
      - name: Build
        run: bash bin/deploy/gh-pages.sh
        env:
          GH_PAGES_BASE: /laravel-reservation-management-system
          GH_PAGES_TRACKING_ID: UA-78163306-3
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ${{ GH_PAGES_DIR }}
      - uses: 8398a7/action-slack@v1
        with:
          type: failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()

  slack:
    name: Slack
    needs: [pages, releases]
    runs-on: ubuntu-latest
    steps:
      - uses: 8398a7/action-slack@v1
        with:
          type: success
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
